export const MM_PER_INCH = 25.4;
export const OBJECTIVE_MARKER_DIAMETER_MM = 40;
export const OBJECTIVE_MARKER_RADIUS = (OBJECTIVE_MARKER_DIAMETER_MM / MM_PER_INCH) / 2;
export const OBJECTIVE_CONTROL_DISTANCE = 3;
export const OBJECTIVE_CONTROL_RADIUS = OBJECTIVE_MARKER_RADIUS + OBJECTIVE_CONTROL_DISTANCE;
